### ISSUE TITLE
Can process ArrayableInterface with Json::encode(), like Yii2 ?

### ISSUE THREAD

**Issue by niqingyang** [yiisoft/json#45]
### What steps will reproduce the problem?

Json::encode()  did not handle the object of ArrayableInterface, like Yii2

```php
/**
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $phone
 */
class User implements ArrayableInterface
{
    use ArrayableTrait;

   public ?int $id = null;

   public ?string $name = null;

   public ?string $phone = null;

    public function toArray(array $fields = [], array $expand = [], bool $recursive = true): array
    {
        return [
           'demo' => 'demo'
        ];
    }
}

$user = new User();
$user->id = 1;
$user->name = 'xxx';
$user->phone = 'xxx';

$data = Json::decode(Json::encode($user));

echo $data['demo'];

```

### What is the expected result?

```php
'demo'
```

### What do you get instead?

```php
null
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.1
| Operating system | Windows 10

**Comment by Tigrov** [comment]
`Json::encode()` supports `JsonSerializable` interface. Needs to add `JsonSerializable` to the class interfaces.

```php
class User implements ArrayableInterface, JsonSerializable
{
...
    public function jsonSerialize(): mixed
    {
        return $this->toArray();
    }
...
}
```

**Comment by niqingyang** [comment]
> `Json::encode()` supports `JsonSerializable` interface. Needs to add `JsonSerializable` to the class interfaces.
> 
> ```
> class User implements ArrayableInterface, JsonSerializable
> {
> ...
>     public function jsonSerialize(): mixed
>     {
>         return $this->toArray();
>     }
> ...
> }
> ```

ok

**Comment by vjik** [comment]
Also we can add support `ArrayableInterface` (`yiisoft/arrays` will be optional dependency):

```php
if ($data instanceof ArrayableInterface) {
	return self::processArray($data->toArray());
}
```

Does that make sense? Are there any cases when object with `ArrayableInterface` should be serialized to json in different way?

**Comment by Tigrov** [comment]
> Does that make sense? Are there any cases when object with `ArrayableInterface` should be serialized to json in different way?

I'm for explicit conversion to `json` using `JsonSerializable::jsonSerialize()`.

For example, `ActiveRecord` objects will be converted using `ActiveRecord::getAttributes()`, but if to support `ArrayableInterface` inside `Json::encode()` the result will be different.

```php
class Model extends ActiveRecord
{
    ...
    public function fields(): array
    {
        return [
            'firstName' => 'first_name',
            'lastName' => 'last_name',
        ];
    }
}
```

Result for current implementation
```php
$json = Json::encode($model);
// {"first_name":"John","last_name":"Smith"}
```

Result if to support `ArrayableInterface`
```php
$json = Json::encode($model);
// {"firstName":"John","lastName":"Smith"}
```
